### ISSUE TITLE
working vim in an ssh2 session, terminal screen does not update properly.

### ISSUE THREAD

**Issue by letsview** [QQxiaoming/quardCRT#40] opened 2024-06-07 12:34 UTC
**Describe the bug**
After working with vim in an ssh2 session and exiting, the terminal screen does not update properly.

**To Reproduce**
1. Connect to other Linux with SSH2 session.
2. Go to anywhere
3. Exit after editing text file with VIM.
4. Type 'Enter' command continuously on shell.

**Expected behavior**
The screen should be neatly updated.

**Screenshots**
![image](https://github.com/QQxiaoming/quardCRT/assets/172039585/88beb56d-dc28-4fb2-9be3-587a93fd5b02)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Version V0.4.6

**Additional context**

**Comment by QQxiaoming** [comment] 2024-06-11 02:30
I tried many times but failed to reproduce this issue. I guess it might be caused by broken window `resize`.
Have you tried to resize the window after this error occurs? What happens?

**Comment by letsview** [comment] 2024-06-11 07:19
The problem is solved by opening the text file with VIM and then adjusting the window size.
As shown in the following image, the size of the editing window when opening a document with VIM for the first time seems to be related.
![image](https://github.com/QQxiaoming/quardCRT/assets/172039585/2574319d-4248-42f5-af50-95cc77dbd86c)

**Comment by QQxiaoming** [comment] 2024-06-11 10:03
> The problem is solved by opening the text file with VIM and then adjusting the window size. As shown in the following image, the size of the editing window when opening a document with VIM for the first time seems to be related. ![image](https://private-user-images.githubusercontent.com/172039585/338477489-2574319d-4248-42f5-af50-95cc77dbd86c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTk1NjMsIm5iZiI6MTcxODA5OTI2MywicGF0aCI6Ii8xNzIwMzk1ODUvMzM4NDc3NDg5LTI1NzQzMTlkLTQyNDgtNDJmNS1hZjUwLTk1Y2M3N2RiZDg2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwOTQ3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDRjNjZkM2I0MDMyY2I4MjQ2MzhjODg1NTBjMTRiODdlMWEwMjAyZjJmMTE2NWNhYmMwM2I3OGI5NmU2MTJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Nd9SZ9aODp7O1Vxpw2AqZYRE7ClHVKPULxdmEG9PsBU)

I think my latest commit ea773b2 may have fixed this issue. The original logic was to use a fixed terminal size of 80x24 after establishing the ssh connection, and resize sshpty according to the window size after 100ms. However, if the link establishment time is greater than 100ms, the resize will be ignored, resulting in the final size staying at 80x24, which is exactly the same as the situation in the screenshot. ea773b2 has now fixed this problem and will use the correct window size when initializing the connection.

Before,

https://github.com/QQxiaoming/quardCRT/blob/0315f435c173fb558b1663e7f2bb45c6a16c5575/lib/qtssh/sshshell.cpp#L119
https://github.com/QQxiaoming/quardCRT/blob/0315f435c173fb558b1663e7f2bb45c6a16c5575/src/sessionswindow/sessionswindow.cpp#L335-L337

Now,

https://github.com/QQxiaoming/quardCRT/blob/ea773b20ce6f54943f0b562498eb23563e7ba21f/lib/qtssh/sshshell.cpp#L121

**Comment by QQxiaoming** [comment] 2024-06-26 05:24
[V0.4.7](https://github.com/QQxiaoming/quardCRT/releases/tag/V0.4.7) is now available, which should resolve this issue.

**Closed by QQxiaoming** 2024-06-26 05:24 UTC
Labels: bug
